import type { IBuyChannel, TBuyAudience, TBuyChannelType, TBuyRisk } from '@/types';

type TChannelSeed = {
  id: string;
  type: TBuyChannelType;
  risk: TBuyRisk;
  audiences: TBuyAudience[];
  href?: string;
  zh: { title: string; description: string; price: string; outcome: string; notes?: string };
  en: { title: string; description: string; price: string; outcome: string; notes?: string };
};

const CHANNELS: TChannelSeed[] = [
  {
    id: 'openai',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://platform.openai.com',
    zh: { title: 'OpenAI 官方（API / 账单）', description: '官方渠道，条款清晰、可追溯。', price: '按量计费（以官网为准）', outcome: '稳定、可审计', notes: 'https://platform.openai.com' },
    en: { title: 'OpenAI (official)', description: 'Official billing & API access.', price: 'Usage-based (refer to official)', outcome: 'Most traceable', notes: 'https://platform.openai.com' },
  },
  {
    id: 'anthropic',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://console.anthropic.com',
    zh: { title: 'Anthropic 官方（Claude API）', description: '官方渠道，适合需要 Claude 的团队。', price: '按量计费（以官网为准）', outcome: '条款清楚、续费/支持更稳定', notes: 'https://console.anthropic.com' },
    en: { title: 'Anthropic (official)', description: 'Official Claude API console.', price: 'Usage-based (refer to official)', outcome: 'Clear terms and support', notes: 'https://console.anthropic.com' },
  },
  {
    id: 'google-ai-studio',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team'],
    href: 'https://aistudio.google.com',
    zh: { title: 'Google AI Studio（Gemini）', description: 'Google 官方入口，适合个人/小团队快速验证。', price: '按量计费/套餐（以官网为准）', outcome: '上手快，适合原型', notes: 'https://aistudio.google.com' },
    en: { title: 'Google AI Studio (Gemini)', description: 'Official entry for quick prototyping.', price: 'Usage-based/plans (refer to official)', outcome: 'Fast iteration', notes: 'https://aistudio.google.com' },
  },
  {
    id: 'azure-openai',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://azure.microsoft.com/products/ai-services/openai-service',
    zh: { title: 'Azure OpenAI', description: '走云厂商采购流程，常见于企业合规/审计要求。', price: '云账单（以官网为准）', outcome: '采购/发票/合规更顺', notes: 'https://azure.microsoft.com/products/ai-services/openai-service' },
    en: { title: 'Azure OpenAI', description: 'Enterprise procurement and governance.', price: 'Cloud billing (refer to official)', outcome: 'Better compliance & audit', notes: 'https://azure.microsoft.com/products/ai-services/openai-service' },
  },
  {
    id: 'aws-bedrock',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://aws.amazon.com/bedrock/',
    zh: { title: 'AWS Bedrock', description: '通过 AWS 统一采购/治理多模型。', price: '云账单（以官网为准）', outcome: '统一治理与权限', notes: 'https://aws.amazon.com/bedrock/' },
    en: { title: 'AWS Bedrock', description: 'Unified procurement & governance for multiple models.', price: 'Cloud billing (refer to official)', outcome: 'Centralized governance', notes: 'https://aws.amazon.com/bedrock/' },
  },
  {
    id: 'gcp-vertex-ai',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://cloud.google.com/vertex-ai',
    zh: { title: 'Google Vertex AI', description: '企业级模型托管与治理，适合走 GCP 采购。', price: '云账单（以官网为准）', outcome: '治理更可控', notes: 'https://cloud.google.com/vertex-ai' },
    en: { title: 'Google Vertex AI', description: 'Enterprise-grade model hosting and governance.', price: 'Cloud billing (refer to official)', outcome: 'Stronger governance', notes: 'https://cloud.google.com/vertex-ai' },
  },
  {
    id: 'openrouter',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://openrouter.ai',
    zh: {
      title: 'OpenRouter（模型路由/聚合）',
      description: '第三方聚合平台：一个 API 访问多模型。',
      price: '按量计费（以平台为准）',
      outcome: '切模型更方便，但需评估合规与审计',
      notes: 'linux.do 讨论：使用 OpenRouter 时注意 provider 风险与策略变动',
    },
    en: { title: 'OpenRouter (model router)', description: 'One API for multiple models.', price: 'Usage-based (platform billing)', outcome: 'Convenient switching; review compliance', notes: 'https://openrouter.ai' },
  },
  {
    id: 'together',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://www.together.ai',
    zh: { title: 'Together.ai（推理/托管）', description: '第三方推理平台，适合快速接入开源模型。', price: '按量计费（以官网为准）', outcome: '弹性好，注意成本与 SLA', notes: 'https://www.together.ai' },
    en: { title: 'Together.ai', description: 'Inference platform for open models.', price: 'Usage-based (refer to official)', outcome: 'Flexible; watch costs & SLA', notes: 'https://www.together.ai' },
  },
  {
    id: 'groq',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://groq.com',
    zh: { title: 'GroqCloud（推理）', description: '第三方推理服务，偏低延迟/高吞吐使用体验。', price: '按量计费（以官网为准）', outcome: '延迟低，注意模型覆盖与限额', notes: 'https://groq.com' },
    en: { title: 'GroqCloud', description: 'Low-latency inference service.', price: 'Usage-based (refer to official)', outcome: 'Low latency; check model coverage/quotas', notes: 'https://groq.com' },
  },
  {
    id: 'siliconflow',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://siliconflow.cn',
    zh: { title: '硅基流动（SiliconFlow）', description: '国内常见的多模型聚合/推理平台之一。', price: '按量计费/套餐（以平台为准）', outcome: '国内付款更方便，注意审计/日志与数据边界', notes: 'linux.do 关键词：硅基流动 / siliconflow' },
    en: { title: 'SiliconFlow', description: 'China-based multi-model gateway/inference platform.', price: 'Plans/usage-based (platform billing)', outcome: 'Local payment; review data boundaries', notes: 'linux.do keyword: siliconflow' },
  },
  {
    id: 'novita',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://novita.ai',
    zh: { title: 'Novita AI（推理/聚合）', description: '第三方推理平台之一，常被用于多模型试用与接入。', price: '按量计费/赠金活动（以平台为准）', outcome: '接入快，注意可用模型与风控策略', notes: 'linux.do 关键词：Novita / novita' },
    en: { title: 'Novita AI', description: 'Inference platform often used for quick evaluation.', price: 'Usage-based/credits (platform billing)', outcome: 'Fast start; check policies', notes: 'linux.do keyword: novita' },
  },
  {
    id: 'nebius',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['team', 'enterprise', 'individual'],
    href: 'https://nebius.com',
    zh: { title: 'Nebius（推理/云平台）', description: '第三方云/推理平台之一，提供多模型与算力相关服务。', price: '按量计费（以官网为准）', outcome: '供给/价格可能变动，注意账单与配额', notes: 'linux.do 关键词：nebius' },
    en: { title: 'Nebius', description: 'Cloud/inference platform with multiple model offerings.', price: 'Usage-based (refer to official)', outcome: 'Validate quotas and billing', notes: 'linux.do keyword: nebius' },
  },
  {
    id: 'deepinfra',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://deepinfra.com',
    zh: { title: 'DeepInfra（推理/托管）', description: '第三方推理与模型 API 平台：多模型入口。', price: '按量计费（以平台为准）', outcome: '试验快，注意 SLA/数据策略', notes: 'https://deepinfra.com' },
    en: { title: 'DeepInfra', description: 'Inference and model API platform.', price: 'Usage-based (platform billing)', outcome: 'Fast experiments; review policies', notes: 'https://deepinfra.com' },
  },
  {
    id: 'fireworks',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://fireworks.ai',
    zh: { title: 'Fireworks.ai（推理/托管）', description: '第三方推理平台，适合快速接入多模型与评估。', price: '按量计费（以官网为准）', outcome: '上手快，注意成本曲线', notes: 'https://fireworks.ai' },
    en: { title: 'Fireworks.ai', description: 'Inference platform for quick evaluation.', price: 'Usage-based (refer to official)', outcome: 'Fast to start; watch costs', notes: 'https://fireworks.ai' },
  },
  {
    id: 'replicate',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://replicate.com',
    zh: { title: 'Replicate（模型托管）', description: '第三方模型托管/调用平台，常用于原型与实验。', price: '按量计费（以官网为准）', outcome: '原型友好，注意生产可用性', notes: 'https://replicate.com' },
    en: { title: 'Replicate', description: 'Model hosting and inference for prototyping.', price: 'Usage-based (refer to official)', outcome: 'Great for prototypes; validate production needs', notes: 'https://replicate.com' },
  },
  {
    id: 'huggingface',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://huggingface.co',
    zh: { title: 'Hugging Face（推理/托管）', description: '模型生态与推理入口（含多种推理提供方）。', price: '按量计费/套餐（以官网为准）', outcome: '生态丰富，注意权限与数据边界', notes: 'https://huggingface.co' },
    en: { title: 'Hugging Face (inference)', description: 'Ecosystem + inference entry with multiple providers.', price: 'Plans/usage-based (refer to official)', outcome: 'Rich ecosystem; review data boundaries', notes: 'https://huggingface.co' },
  },
  {
    id: 'mistral',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://console.mistral.ai',
    zh: { title: 'Mistral 官方（API）', description: '官方 API 入口，适合需要 Mistral 模型的团队。', price: '按量计费（以官网为准）', outcome: '条款清楚、可追溯', notes: 'https://console.mistral.ai' },
    en: { title: 'Mistral (official)', description: 'Official API console.', price: 'Usage-based (refer to official)', outcome: 'Traceable terms', notes: 'https://console.mistral.ai' },
  },
  {
    id: 'cohere',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://cohere.com',
    zh: { title: 'Cohere 官方（API）', description: '官方 API 入口，偏企业场景与可控部署选项。', price: '按量计费/合同（以官网为准）', outcome: '企业采购更顺', notes: 'https://cohere.com' },
    en: { title: 'Cohere (official)', description: 'Official API with enterprise focus.', price: 'Usage/contract (refer to official)', outcome: 'Enterprise-friendly', notes: 'https://cohere.com' },
  },
  {
    id: 'deepseek',
    type: 'official',
    risk: 'low',
    audiences: ['individual', 'team', 'enterprise'],
    href: 'https://api-docs.deepseek.com',
    zh: { title: 'DeepSeek 官方（API）', description: '国内外开发者常用的模型 API 入口之一。', price: '按量计费（以官网为准）', outcome: '接入快，注意限额与稳定性', notes: 'https://api-docs.deepseek.com' },
    en: { title: 'DeepSeek (official)', description: 'Official API docs and access.', price: 'Usage-based (refer to official)', outcome: 'Fast integration; check quotas', notes: 'https://api-docs.deepseek.com' },
  },
  {
    id: 'zhipu',
    type: 'official',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://open.bigmodel.cn',
    zh: { title: '智谱 AI（API）', description: '国内模型平台之一，适合走本地付款/开票流程。', price: '按量计费/合同（以官网为准）', outcome: '采购更顺，注意模型能力与价格曲线', notes: 'https://open.bigmodel.cn' },
    en: { title: 'Zhipu AI (official)', description: 'China-based model API platform.', price: 'Usage/contract (refer to official)', outcome: 'Procurement-friendly; validate capability', notes: 'https://open.bigmodel.cn' },
  },
  {
    id: 'volcengine-ark',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://www.volcengine.com/product/ark',
    zh: { title: '火山方舟（国内合规采购）', description: '国内云平台大模型入口，适合企业采购与对接。', price: '云账单（以官网为准）', outcome: '合同/发票更顺', notes: 'https://www.volcengine.com/product/ark' },
    en: { title: 'Volcengine Ark', description: 'China-based enterprise AI platform.', price: 'Cloud billing (refer to official)', outcome: 'Procurement-friendly', notes: 'https://www.volcengine.com/product/ark' },
  },
  {
    id: 'cloudflare-workers-ai',
    type: 'marketplace',
    risk: 'medium',
    audiences: ['individual', 'team'],
    href: 'https://developers.cloudflare.com/workers-ai/',
    zh: { title: 'Cloudflare Workers AI', description: '边缘推理与一体化部署入口。', price: '按量计费（以官网为准）', outcome: '部署方便，注意模型能力边界', notes: 'https://developers.cloudflare.com/workers-ai/' },
    en: { title: 'Cloudflare Workers AI', description: 'Edge inference with simple deployment.', price: 'Usage-based (refer to official)', outcome: 'Easy deployment; check model limits', notes: 'https://developers.cloudflare.com/workers-ai/' },
  },
  {
    id: 'china-bailian',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://bailian.console.aliyun.com',
    zh: { title: '阿里云百炼（国内合规采购）', description: '国内云厂商大模型平台，适合需要发票/合同的团队。', price: '云账单（以官网为准）', outcome: '本地付款/发票/合同更顺', notes: 'https://bailian.console.aliyun.com' },
    en: { title: 'Alibaba Cloud Bailian', description: 'China-based enterprise procurement.', price: 'Cloud billing (refer to official)', outcome: 'Better local procurement workflow', notes: 'https://bailian.console.aliyun.com' },
  },
  {
    id: 'china-qianfan',
    type: 'enterprise',
    risk: 'low',
    audiences: ['team', 'enterprise'],
    href: 'https://console.bce.baidu.com/qianfan/overview',
    zh: { title: '百度智能云千帆（国内合规采购）', description: '国内大模型平台，适合走企业采购流程。', price: '云账单（以官网为准）', outcome: '合规/采购对接更便利', notes: 'https://console.bce.baidu.com/qianfan/overview' },
    en: { title: 'Baidu Qianfan', description: 'China-based enterprise AI platform.', price: 'Cloud billing (refer to official)', outcome: 'Procurement-friendly', notes: 'https://console.bce.baidu.com/qianfan/overview' },
  },
  {
    id: 'risky-unofficial',
    type: 'risky',
    risk: 'high',
    audiences: ['individual', 'team'],
    zh: {
      title: '非授权“代充/中转/共享账号”',
      description: '信息不可追溯、条款不清晰，存在封禁/资金/数据风险。',
      price: '看似更便宜',
      outcome: '高概率踩坑（不建议）',
      notes: '建议仅选择官方/授权/云厂商可审计路径；如必须评估第三方，先做资质与合同/发票核验。',
    },
    en: {
      title: 'Unofficial resellers / shared accounts',
      description: 'Hard to audit; unclear terms; higher ban/financial/data risks.',
      price: 'Looks cheaper',
      outcome: 'High risk (not recommended)',
      notes: 'Prefer official/authorized/cloud procurement with audit trails.',
    },
  },
];

export function getBuyChannels(language: 'zh' | 'en'): IBuyChannel[] {
  return CHANNELS.map((item) => {
    const localized = language === 'en' ? item.en : item.zh;
    return {
      id: item.id,
      type: item.type,
      risk: item.risk,
      audiences: item.audiences,
      href: item.href,
      title: localized.title,
      description: localized.description,
      price: localized.price,
      outcome: localized.outcome,
      notes: localized.notes,
    };
  });
}
